blueprint:
  name: Test
  description: Test, Test, Test, Test, Test, Test, Test, Test, Test
  domain: automation
  author: RalfEs73
  source_url: https://raw.githubusercontent.com/RalfEs73/ha_blueprints/refs/heads/main/test.yaml
  input:
    light_target:
      name: Licht
      selector:
        target:
          entity:
            domain: light
