blueprint:
  name: Test
  description: Test3, Test, Test, Test, Test, Test, Test, Test, Test
  domain: automation
  author: RalfEs73
  source_url: https://raw.githubusercontent.com/RalfEs73/ha_blueprints/refs/heads/main/test.yaml
  input:
    schalter_target:
      name: Schalter
      default: {}
      selector:
        target:
          entity:
          - domain:
            - boolean
    light_target:
      name: Licht
      default: {}
      selector:
        target:
          entity:
          - domain:
            - light


triggers:
  trigger: state
  entity_id: !input schalter_target
  from: "off"
  to: "on"

actions:
  - alias: "Turn off the light"
    action: light.turn_off
    target: !input light_target